[build]
  functions = "netlify/functions"
  publish = "dist"
  command = "npm install && npm run build"
  
[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  
[functions]
  node_bundler = "esbuild"

# Headers for CORS and security
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment context - ensure dev dependencies are available for builds
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development" 