[build]
  functions = "netlify/functions"
  publish = "dist"
  command = "npm ci --production=false && npm run build"
  
[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  NPM_CONFIG_PRODUCTION = "false"
  # Supabase environment variables should be set in Netlify dashboard:
  # VITE_SUPABASE_URL = "https://jyuafqzjrzifqbgcqbnt.supabase.co"
  # VITE_SUPABASE_ANON_KEY = " eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5dWFmcXpqcnppZnFiZ2NxYm50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxOTQ2MTQsImV4cCI6MjA2NDc3MDYxNH0.5bieHY8DpC1x5suSg_2jZB5NusQLsCzfeczR06XVuZU"
  
[functions]
  node_bundler = "esbuild"

# Headers for CORS and security
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment context - ensure dev dependencies are available for builds
[context.production.environment]
  NODE_ENV = "production"
  NPM_CONFIG_PRODUCTION = "false"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development" 